### ISSUE TITLE
Would you use node 0.12.x in production?

### ISSUE THREAD

**Issue by paulja** [cmilhench/ama#2]
And, what about io.js?

**Comment by cmilhench** [comment]
The short answer is **no**.  

Great strides are being made to consolidate node.js and io.js, I expect there to be only one prominent version of node in the not too distant future, however it doesn't look like 0.12 or io.js are going to be production ready soon. 

Version 0.10 is by far the most stable release available.  So for a production project *right now*, 0.10 is where it's at.

I'll bee keeping my eyes on developments though...
